import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from backend.app.models.user import User
from backend.app.models.workout import ExerciseSession, Workout, WorkoutStatus


@pytest.mark.asyncio
async def test_analytics_summary_unauthenticated(async_client: AsyncClient):
    """Verify unauthenticated requests to analytics endpoints are rejected with 401."""
    res = await async_client.get("/api/v1/analytics/summary")
    assert res.status_code == 401


@pytest.mark.asyncio
async def test_analytics_summary_empty_user(authenticated_async_client: AsyncClient):
    """Verify an athlete with no workouts receives a clean 200 with zero metrics."""
    res = await authenticated_async_client.get("/api/v1/analytics/summary")
    assert res.status_code == 200
    data = res.json()
    assert data["total_workouts"] == 0
    assert data["total_reps"] == 0
    assert data["total_valid_reps"] == 0
    assert data["valid_rep_percentage"] == 100.0
    assert data["average_form_score"] == 0.0
    assert data["exercise_breakdown"] == []


@pytest.mark.asyncio
async def test_analytics_summary_and_trends_with_data(
    authenticated_async_client: AsyncClient,
    test_user: User,
    db_session: AsyncSession,
):
    """Verify analytics summary and trends return accurate aggregated numbers from DB."""
    # Create workout for test_user
    w = Workout(
        user_id=test_user.id,
        status=WorkoutStatus.COMPLETED,
        total_duration_sec=300.0,
        overall_form_score=94.0,
    )
    db_session.add(w)
    await db_session.flush()

    s = ExerciseSession(
        workout_id=w.id,
        exercise_name="squat",
        completed_reps=10,
        valid_reps=10,
        invalid_reps=0,
        average_form_score=94.0,
    )
    db_session.add(s)
    await db_session.commit()

    # Query summary
    summary_res = await authenticated_async_client.get("/api/v1/analytics/summary")
    assert summary_res.status_code == 200
    summary = summary_res.json()
    assert summary["total_workouts"] == 1
    assert summary["total_reps"] == 10
    assert summary["total_valid_reps"] == 10
    assert summary["average_form_score"] == 94.0
    assert summary["most_practiced_exercise"] == "squat"
    assert len(summary["exercise_breakdown"]) == 1
    assert summary["exercise_breakdown"][0]["exercise_name"] == "squat"

    # Query exercise analytics
    ex_res = await authenticated_async_client.get("/api/v1/analytics/exercises/squat")
    assert ex_res.status_code == 200
    ex_data = ex_res.json()
    assert ex_data["exercise_name"] == "squat"
    assert ex_data["total_reps"] == 10
    assert ex_data["valid_reps"] == 10
    assert ex_data["best_form_score"] == 94.0

    # Query trends
    trends_res = await authenticated_async_client.get("/api/v1/analytics/trends?period=all")
    assert trends_res.status_code == 200
    trends = trends_res.json()
    assert trends["total_points"] == 1
    assert trends["points"][0]["form_score"] == 94.0
    assert trends["points"][0]["total_reps"] == 10


@pytest.mark.asyncio
async def test_analytics_cross_user_isolation(
    authenticated_async_client: AsyncClient,
    second_user: User,
    db_session: AsyncSession,
):
    """Verify User A cannot see workouts or stats generated by User B in analytics."""
    # Create workout owned by second_user
    w = Workout(
        user_id=second_user.id,
        status=WorkoutStatus.COMPLETED,
        total_duration_sec=900.0,
        overall_form_score=98.0,
    )
    db_session.add(w)
    await db_session.flush()

    s = ExerciseSession(
        workout_id=w.id,
        exercise_name="shoulder_press",
        completed_reps=50,
        valid_reps=50,
        invalid_reps=0,
        average_form_score=98.0,
    )
    db_session.add(s)
    await db_session.commit()

    # authenticated_async_client is logged in as test_user
    res = await authenticated_async_client.get("/api/v1/analytics/summary")
    assert res.status_code == 200
    summary = res.json()
    assert summary["total_workouts"] == 0
    assert summary["total_reps"] == 0
    assert summary["most_practiced_exercise"] is None
